# Generated by Django 4.2.6 on 2023-10-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passsword',
            new_name='password',
        ),
    ]
