# Generated by Django 4.2.6 on 2023-11-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_status',
            new_name='payment_status',
        ),
    ]
