# Generated by Django 4.2.6 on 2023-11-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_product_status_cart_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_price',
        ),
    ]
